CREATE DATABASE COFFEESHOPMANAGERSs
GO
USE COFFEESHOPMANAGERSs
GO 
-- FOOD 
-- TABLE
-- FOODCATEGORY
-- ACCOUNT
-- BILL
-- BILLINFO

CREATE TABLE TABLEs(
ID INT IDENTITY PRIMARY KEY ,
NAME NVARCHAR(100) NOT NULL DEFAULT N'BAN CHU CO TEN',
STATUS NVARCHAR(100) NOT NULL DEFAULT N'Trống'
)
GO

CREATE TABLE ACCOUNTs(
USERNAME NVARCHAR(100) PRIMARY KEY,
DISPLAYNAME NVARCHAR(100) NOT NULL DEFAULT N'THANH SANG',
PASSWORD NVARCHAR(1000) NOT NULL DEFAULT 0,
TYPE INT NOT NULL DEFAULT 0
)
GO

CREATE TABLE WATERCATEGORYs(
ID INT IDENTITY PRIMARY KEY,
NAME NVARCHAR(100)  NOT NULL DEFAULT N'CHUA DAT TEN'
)
GO

CREATE TABLE WATERs(
ID INT IDENTITY PRIMARY KEY,
NAME NVARCHAR (100) NOT NULL DEFAULT N'CHUA DAT TEN',
IDCATEGORY INT NOT NULL,
PRICE FLOAT NOT NULL DEFAULT 0
FOREIGN KEY (IDCATEGORY) REFERENCES DBO.WATERCATEGORYs(ID)
)
GO

CREATE TABLE BILLs(
ID INT IDENTITY PRIMARY KEY ,
DATECHECKIN DATE NOT NULL DEFAULT GETDATE(),
DATECHECKOUT DATE,
IDTABLE INT NOT NULL,
STATUS INT NOT NULL DEFAULT 0
FOREIGN KEY (IDTABLE) REFERENCES DBO.TABLEs(ID)
)
GO

CREATE TABLE BILLINFOs(
ID INT IDENTITY PRIMARY KEY ,
IDBILL INT NOT NULL,
IDWATER  INT NOT NULL,
COUNT INT NOT NULL DEFAULT 0
FOREIGN KEY (IDBILL) REFERENCES DBO.BILLs(ID),
FOREIGN KEY (IDWATER) REFERENCES DBO.WATERs(ID)
)
GO

INSERT INTO DBO.ACCOUNTs(
USERNAME,
DISPLAYNAME,
PASSWORD,
TYPE
)
VALUES(
N'THANHSANG',
N'HOMAITHANHSANG',
N'2033216533',
1
)

INSERT INTO DBO.ACCOUNTs(
USERNAME,
DISPLAYNAME,
PASSWORD,
TYPE
)
VALUES(
N'GIAMINH',
N'TRANGIAMINH',
N'12',
1
)
GO

CREATE PROC USP_GETACCOUNTUSERNAME
@USERNAME NVARCHAR(100)
AS
BEGIN
SELECT * FROM DBO.ACCOUNTs WHERE USERNAME = @USERNAME
END
GO

EXEC DBO.USP_GETACCOUNTUSERNAME @USERNAME = N'THANHSANG'

SELECT * FROM DBO.ACCOUNTs WHERE USERNAME = N'THANHSANG'

SELECT *FROM DBO.ACCOUNTs WHERE USERNAME = N' ' AND PASSWORD = N''OR	1 = 1--'

---thêm bàn---
DECLARE @I INT = 12
WHILE @I<=20
BEGIN
INSERT DBO.TABLEs(NAME)VALUES(N'BÀN '+ CAST (@I AS NVARCHAR(100))) 
SET @I=@I+1
END 
GO
---thêm category---
INSERT DBO.WATERCATEGORYs (NAME)
VALUES (N'CÀ PHÊ PHA PHIN')
INSERT DBO.WATERCATEGORYs (NAME)
VALUES (N'TRÀ')
INSERT DBO.WATERCATEGORYs (NAME)
VALUES (N'FREEZE')
INSERT DBO.WATERCATEGORYs (NAME)
VALUES (N'CÀ PHÊ ESPRESSO')
INSERT DBO.WATERCATEGORYs (NAME)
VALUES (N'BÁNH')
INSERT DBO.WATERCATEGORYs (NAME)
VALUES (N'BÁNH MÌ')
INSERT DBO.WATERCATEGORYs (NAME)
VALUES (N'THỨC UỐNG KHÁC')
---thêm món ăn---
INSERT DBO.WATERs(NAME,IDCATEGORY,PRICE)
VALUES (N'PHIN Sữa Đá',1,27000)
INSERT DBO.WATERs(NAME,IDCATEGORY,PRICE)
VALUES (N'PHIN Đen Đá',1,25000)
INSERT DBO.WATERs(NAME,IDCATEGORY,PRICE)
VALUES (N'Bạc Xỉu Đá',1,29000)
---thêm bill---
INSERT DBO.BILLs(DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS)
VALUES (GETDATE(),NULL,1,0)
INSERT DBO.BILLs(DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS)
VALUES (GETDATE(),NULL,2,0)
INSERT DBO.BILLs(DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS)
VALUES (GETDATE(),GETDATE(),2,1)
INSERT DBO.BILLs(DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS)
VALUES (GETDATE(),GETDATE(),3,0)
--Thêm Billinfo--
INSERT DBO.BILLINFOs(IDBILL,IDWATER,COUNT)
VALUES (1,1,2)
INSERT DBO.BILLINFOs(IDBILL,IDWATER,COUNT)
VALUES (1,3,4)
INSERT DBO.BILLINFOs(IDBILL,IDWATER,COUNT)
VALUES (2,3,4)
INSERT DBO.BILLINFOs(IDBILL,IDWATER,COUNT)
VALUES (3,3,4)

SELECT *FROM DBO.BILLs WHERE IDTABLE = 3 AND STATUS = 0

SELECT *FROM DBO.BILLINFOs WHERE IDBILL = 2

	 

	SELECT * FROM DBO.BILLINFOs AS BI, DBO.BILLs AS B, DBO.WATERs AS W
	WHERE BI.IDBILL=B.ID AND BI.IDWATER=W.ID AND B.IDTABLE = 1
SELECT *FROM DBO.TABLEs
UPDATE DBO.TABLEs SET STATUS =N'Có Người' WHERE ID = 9
GO
INSERT DBO.TABLEs
(NAME,STATUS)
VALUES (N'BÀN 1')